"""v2

Revision ID: 00ca7fd09ea0
Revises: 8896d3fd8922
Create Date: 2024-01-19 13:05:07.483239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ca7fd09ea0'
down_revision: Union[str, None] = '8896d3fd8922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('submenu_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'menu', 'submenu', ['submenu_id'], ['id'])
    op.add_column('submenu', sa.Column('dish_id', sa.UUID(), nullable=False))
    op.add_column('submenu', sa.Column('menu_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'submenu', 'dish', ['dish_id'], ['id'])
    op.create_foreign_key(None, 'submenu', 'menu', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submenu', type_='foreignkey')
    op.drop_constraint(None, 'submenu', type_='foreignkey')
    op.drop_column('submenu', 'menu_id')
    op.drop_column('submenu', 'dish_id')
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.drop_column('menu', 'submenu_id')
    # ### end Alembic commands ###
