"""added_relationships

Revision ID: 3e5d4a0f9651
Revises: dd8b28e0c6c5
Create Date: 2024-01-24 23:16:14.896209

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e5d4a0f9651"
down_revision: Union[str, None] = "dd8b28e0c6c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
