"""updated

Revision ID: b574d1873768
Revises: e25e6789b4ff
Create Date: 2024-02-08 16:13:10.449368

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = 'b574d1873768'
down_revision: str | None = 'e25e6789b4ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
