"""init
Revision ID: dd8b28e0c6c5
Revises:
Create Date: 2024-01-24 22:11:38.734177
"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = 'dd8b28e0c6c5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
