"""finish

Revision ID: e25e6789b4ff
Revises: 1a32a6cf4f07
Create Date: 2024-02-08 14:06:50.497727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25e6789b4ff'
down_revision: Union[str, None] = '1a32a6cf4f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
