version: "3.8"
services:
  db:
    image: postgres:15
    container_name: postgres
    # volumes:
    #   - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env.psql
    ports:
      - 1234:5432

  restaurant_app:
    image: restaurant_app
    build:
      context: .
    container_name: rest_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:8000
