version: "3.8"
services:
  test_db:
    image: postgres:15.1-alpine
    container_name: test_postgres
    env_file:
      - .env_test
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASS}
      - POSTGRES_DB=${TEST_DB_NAME}
    ports:
      - 4321:5432

    healthcheck:
      test: pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

  test_restaurant_app:
    image: test_restaurant_app
    build:
      context: .
    container_name: test_rest_app
    env_file:
      - .env_test
    depends_on:
      test_db:
        condition: service_healthy
    ports:
      - 9000:8000
