version: "3.8"
services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 1234:5432
    networks:
      - my_network
    volumes:
      - psql_network:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

  restaurant_app:
    image: restaurant_app
    build:
      context: .
    container_name: rest_app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    networks:
      - my_network

networks:
  my_network:
    name: my_network
volumes:
  psql_network:
    name: psql_network